### ISSUE TITLE
Confusing names vectorclock:gt und vectorclock:strict_ge

### ISSUE THREAD

**Issue by peterzeller** [SyncFree/antidote_utils#2]
I think `vectorclock:gt` and `vectorclock:lt` should be renamed or removed, since they don't define the standard greater-than and less-than operations on vectorclocks, but a very unusual operation. `vectorclock:strict_ge` and `vectorclock:strict_le` are the standard operations, but the name "strict greater or equal" is confusing. 

I would suggest the following renames:

| old name | new name |
| --- | --- |
| `strict_le` | `lt` or `strict_lt` |
| `strict_ge` | `gt` or `strict_gt` |
| `lt` | `all_dots_smaller` |
| `gt` | `all_dots_greater` |

**Comment by aletomsic** [comment]
Hi, I've done the following:

old name    new name
strict_le   lt
strict_ge   gt
lt  all_dots_smaller
gt  all_dots_greater

I've updated antidote accordingly.

**Comment by aletomsic** [comment]
addressed in PR #6
